services:
  earnfm-client:
    # Official EarnFM client image
    image: earnfm/earnfm-client:latest
    env_file:
      - .env
    container_name: earnfm-client

    # Environment variables for EarnFM token
    environment:
      - EARNFM_TOKEN=${EARNFM_TOKEN}

    restart: always
